
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrlxlbolqoilrnpeelui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybHhsYm9scW9pbHJucGVlbHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTAxNDcsImV4cCI6MjA2MTg4NjE0N30.4KqtwoGCTc0noktr87uMdBW9K4uCnCAAwuR7E7syVuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'pharos_auth',
    persistSession: true,
    autoRefreshToken: true,
  }
});
